[package]
name = "btree-rs"
version = "0.1.0"
authors = ["louchenyao <louchenyao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]

[dev-dependencies]
rand = "0.7.0"